service: events-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
