service: events-api

plugins:
    - serverless-offline
    - serverless-iam-roles-per-function
    - serverless-export-outputs

package:
    individually: true # an optimized package per function

custom:
    exportOutputs:
        include: # export these variables so we can use them in integration tests
            - ServiceEndpoint
            - EventsTableName
        output:
            file: sls-output.json
            format: json

provider:
    name: aws
    runtime: nodejs22.x
    region: eu-central-1
    timeout: 10
    logRetentionInDays: 7
    environment:
        EVENTS_TABLE_NAME: !Ref EventsTable
        POWERTOOLS_SERVICE_NAME: events-api

build:
    esbuild:
        bundle: true
        minify: true
        sourcemap: true
        # @aws-sdk/* packages are automatically excluded

functions:
    getAllEvents:
        handler: src/functions/get-all-events.handler
        events:
            - http:
                  path: events
                  method: get
        iamRoleStatements:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt EventsTable.Arn

    getEvent:
        handler: src/functions/get-event.handler
        events:
            - http:
                  path: events/{id}
                  method: get
        iamRoleStatements:
            - Effect: Allow
              Action: dynamodb:GetItem
              Resource: !GetAtt EventsTable.Arn

    createEvent:
        handler: src/functions/create-event.handler
        events:
            - http:
                  path: events
                  method: post
        iamRoleStatements:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt EventsTable.Arn

    updateEvent:
        handler: src/functions/update-event.handler
        events:
            - http:
                  path: events
                  method: put
        iamRoleStatements:
            - Effect: Allow
              Action: dynamodb:UpdateItem
              Resource: !GetAtt EventsTable.Arn

    deleteEvent:
        handler: src/functions/delete-event.handler
        events:
            - http:
                  path: events/{id}
                  method: delete
        iamRoleStatements:
            - Effect: Allow
              Action: dynamodb:DeleteItem
              Resource: !GetAtt EventsTable.Arn

resources:
    Resources:
        EventsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                BillingMode: PAY_PER_REQUEST
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH

    Outputs:
        EventsTableName:
            Value: !Ref EventsTable
