name: Build, Test and Deploy the API

on:
    push:
        branches:
            - main

env:
    NODE_VERSION: 22
    AWS_REGION: eu-central-1

# Need ID token write permission to use OIDC
permissions:
    id-token: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps: # todo: extract setup steps into a separate file
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Project Dependencies
              run: npm ci

            - name: Audit
              run: npm audit

            - name: Build
              run: npm run build

    test:
        needs: build
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Serverless Framework
              run: npm install -g serverless

            - name: Install Project Dependencies
              run: npm ci

            - name: Unit tests
              run: npm run test

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  role-to-assume: arn:aws:iam::053412160478:role/github-actions-role

            - name: Deploy int env
              run: serverless deploy --stage int

            - name: Integration tests
              run: npm run test-integration

    deploy:
        needs: test
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install Serverless Framework # todo: can we do this globally, once?
              run: npm install -g serverless

            - name: Install Project Dependencies # todo: can we do this globally, once?
              run: npm ci

            - name: Configure AWS Credentials # todo: can we do this globally, once?
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  role-to-assume: arn:aws:iam::053412160478:role/github-actions-role

            - name: Deploy prod env
              run: serverless deploy --stage prod
