name: Build, Test and Deploy the API

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'

env:
    NODE_VERSION: 22
    AWS_REGION: eu-central-1
    SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

# Need ID token write permission to use OIDC
permissions:
    id-token: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/nodejs-setup-action

            - name: Audit
              run: npm audit

            - name: Build
              run: npm run build

    test:
        needs: build
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/nodejs-setup-action

            - name: Unit tests
              run: npm run test

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  role-to-assume: arn:aws:iam::053412160478:role/github-actions-role

            - name: Deploy test environment
              run: npm run deploy:test

            - name: Integration tests
              run: npm run test:integration
              env:
                  EVENTS_API_KEY: ${{ secrets.TEST_EVENTS_API_KEY }}

    deploy:
        needs: test
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup
              uses: ./.github/actions/nodejs-setup-action

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  role-to-assume: arn:aws:iam::053412160478:role/github-actions-role

            - name: Deploy prod environment
              run: npm run deploy:prod
